apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: nginx
spec:
  selector:
    app: notes-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
